### ISSUE TITLE
How hard would be to integrate with ESPHome?

### ISSUE THREAD

**Issue by ashald** [Romkabouter/ESP32-Rhasspy-Satellite#61]
Thanks a lot for an amazing work!
I'm trying to install it on my MATRIX devices and thought it would be amazing if it could be used together with
[ESPHome](https://esphome.io), which provides a super neat way to build firmware for ESP based on desired modules.

**Comment by Romkabouter** [comment]
What is your vision that this software should do within ESPHome?

**Comment by ashald** [comment]
My apologies for not providing enough details.

ESPHome provides a simple way to configure ESP32-based devices. As the use, I can write a simple YAML config that enables desired modules. From there on, ESPHome combines source code for the selected modules, configures them according to what I entered in the YAML config, compiles the firmware and flashes the device.

The extra benefit is that ESPHome integrates with systems like HomeAssistant which makes it breeze to wire things together.
While flashing instructions for [Matrix Voice](https://github.com/Romkabouter/ESP32-Rhasspy-Satellite/blob/master/matrixvoice.md) do not sound too complicated, it would be amazing if one could get it flashed even simpler by just providing few lines of config in ESPHome YAML. I'd imagine it'd work equally well for other supported ESP32 devices.

TL;DR: AFAIU, ESPHome would provide a uniform way for flashing `ESP32-Rhasspy-Satellite` onto compatible devices.

**Comment by Romkabouter** [comment]
Yes, I know a bit of ESPHome.
But the matrix voice cannot by flashed by USB, so that makes it a no-go I guess.

**Comment by ashald** [comment]
Ugh, my bad - IDK how I missed it.
I wish that limitation goes away one day - it would be nuts if we would've been able to flash Matrix Voice with ESPHome, and get `ESP32-Rhasspy-Satellite` on it that way. 😅
Thanks!

**Comment by Romkabouter** [comment]
I saw you can compile and download the firmware. That makes it possible to at least flash ESPHome on the Matrix Voice.
Maybe I'll try something :)

**Comment by Romkabouter** [comment]
Ok, that worked :)

![image](https://user-images.githubusercontent.com/4774478/121768079-6cef8b80-cb5c-11eb-8226-a9f4667c9577.png)

Now what to do with it....

**Comment by ashald** [comment]
Wow, that's amazing! As far as I understand that means that in theory, it's possible to leverage ESPHome for subsequent OTA updates, checking logs, etc. Assuming `ESP32-Rhasspy-Satellite` can be converted into ESPHome-compatible add-on.

P.S.: I wonder if there any chances ESPHome can flash MarixVoice-like devices directly, if they're connected to an RPi via HAT (wishful thinking, ha-ha).

**Comment by Romkabouter** [comment]
> P.S.: I wonder if there any chances ESPHome can flash MarixVoice-like devices directly, if they're connected to an RPi via HAT

That is actually exactly what I did. From Esphome addon, configured a new OTA device:


```
esphome:
  name: matrixvoice
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "SSID"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Matrixvoice Fallback Hotspot"
    password: "generatedpassword"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "apipassword"

ota:
  password: "otapassword"
  
switch:
  - platform: gpio
    name: "Test"
    pin: 5

```
Then, on the right side you have three vertical dots, one f them being "Compile""
After is compiles, you can download the binary.
I renamed it firmware.bin and copied it to my streamer project.
The line cp .pio/build/esp32dev/firmware.bin . had to be commented, but then I executed "sh deploy.sh xxx.xxx.xxx.xxx" which flashed the matrix voice

I have added ESPhome as integration and I have 1 device:
![image](https://user-images.githubusercontent.com/4774478/121775165-3cbce280-cb86-11eb-953a-b49608faaeed.png)
and 1 enitity:

![image](https://user-images.githubusercontent.com/4774478/121775175-5100df80-cb86-11eb-8825-3ef825df42fb.png)
